# 服务端口
server:
  port: 10224

# DML 语句
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.carton.bean
  mapper-locations: classpath:mybatis/mapper/**/*.xml



# 数据库相关配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url : jdbc:mysql://106.52.248.231:10224/redis_cache?characterEncoding=utf-8&useSSL=false
    username: root
    password: xiaochang0324
    platform: mysql
    initialSize: 5
    minIdle: 5
    maxActive: 200
    maxWait: 1200000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT1FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall
    logSlowSql: true
